### ISSUE TITLE
documentation feature request: comparison with Bread::Board

### ISSUE THREAD

**Issue by domm** [loic-prieto/moosex-dic#1]
Hi!

Interesting module with great documentation, but I wonder what the benefits of MooseX::DIC are compared to Bread::Board. Maybe you could add a paragraph or two about that to your documentation.

Greetings,
domm

**Comment by loic-prieto** [comment]
Hi!

Thanks for the suggestion. I´m putting it into the backlog, along with a comparison with other containers in Perl. There´s indeed a reason for why I started this library, other than for the fun of it. Although I´m quite positive that I would have been able to use Bread::Board or Beam::Wire with some customization.

In fact, I was considering this library to be just a layer over one of those two. But then, my developer instinct kicked-in.

**Comment by loic-prieto** [comment]
The differences between MooseX::DIC and other DI frameworks have been documented, and they're available at the [MooseX::DIC Website](http://docs.moosex-dic.org/differences/). 

Thanks for your comment!
